# Generated by Django 5.0.14 on 2026-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_statushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='changed_by',
            field=models.CharField(max_length=255),
        ),
    ]
